variables:
    GRADLE_OPTS: '-Dorg.gradle.daemon=false' # 禁用 gradle 守护进程

before_script:
    - export GRADLE_USER_HOME=/cache/.gradle
    - chmod +x ./gradlew

stages:
    - build
    - deploy

# 提交代码自动编译
build:
    image: jangrewe/gitlab-ci-android
    stage: build
    script:
        - ./gradlew assembleRelease
    only:
        - master
    artifacts:
        paths:
            - app/build/outputs/apk/release/

# 上传至服务器
deploy:
    image: takkatakka/lftp
    stage: deploy
    only:
        - master
    script:
        - bash ./deploy.sh
